### ISSUE TITLE
Groups changing successfully but not ranks

### ISSUE THREAD

**Issue by ProjektPremium** [TheVilleOrg/phpbb-groupsub#40]
I just noticed now that ranks don't change when the groups change. Everything else works perfectly but the ranks that are associated with the groups. Not sure if anybody has pointed it out before.

**Comment by Dark1z** [comment]
Ranks are not handled by this extension,
Kindly check your board settings.

Also close this topic.

Best regards 👍

**Comment by ProjektPremium** [comment]
But aren't ranks attached to groups? But thanks anyway. :)

**Comment by ProjektPremium** [comment]
Actually, I forgot to mention that it actually does change the ranks based on the group. When you start the subscription, it changes both the group and the rank but then when the subscription is over it only changes the group and leaves the previous rank. I think there may be a little bug somewhere maybe worth having a look at?

**Comment by Dark1z** [comment]
This is the part where users are added to group(s) : https://github.com/TheVilleOrg/phpbb-groupsub/blob/dbd8b85af21d3a124c81676b3e41c23d4103f1c6/operator/subscription.php#L639-L759
do you see any handling of ranks in the code ???

Best regards 👍
